import NavigationBar from "@/components/layouts/navbar";
import Footer from "@/components/layouts/footer";
import "./globals.css";

export const metadata = {
  title: "M Iqbal Ferdiansyah",
  description: "Generated by create next app",
  googleSiteVerification: "cmCVVfUe_uvlIc6AIYwZGZfIwpKTpb2SYTfAfCGOTeo",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavigationBar />
        <main className="mx-6 md:mx-16">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
